### ISSUE TITLE
Graphical intermittent stuttering on android UI

### ISSUE THREAD

**Issue by apinela** [Ziyann/android_kernel_asus_grouper#12]

**Comment by lgrootnoob** [comment]
https://github.com/lgrootnoob/android_kernel_asus_grouper/tree/taco
The above branch as a whole fixes the graphical stuttering. A good way to test is the android 6.0 easter egg minigame which stutters before you lose(coming in contact with something). Then test it without my commits and it will stutter. Now clearly one wouldn't use my commits for debugging, but for release. Take that as my only disclaimer.

**Comment by apinela** [comment]
that doesn't fix the real problem.

**Comment by lgrootnoob** [comment]
I figured. Wish I understood the kernel better and could help.

**Comment by apinela** [comment]
BTW good job anyway.
